// 查询数据person
export const PERSONS_FETCH_REQUESTED = 'PERSONS_FETCH_REQUESTED'
// 请求开始
export const PERSONS_FETCH_REQUEST = 'PERSONS_FETCH_REQUEST'
// 请求成功
export const PERSONS_FETCH_SUCCEEDED = 'PERSONS_FETCH_SUCCEEDED'
// 请求失败
export const PERSONS_FETCH_FAILED = 'PERSONS_FETCH_FAILED'

// pull
export const PRESON_PULL_REQUESTED = 'PRESON_PULL_REQUESTED'
// 请求开始
export const PERSON_PULL_REQUEST = 'PERSON_PULL_REQUEST'
// 请求成功
export const PERSON_PULL_SUCCEEDED = 'PERSON_PULL_SUCCEEDED'
// 请求失败
export const PERSON_PULL_FAILED = 'PERSON_PULL_FAILED'

// push
export const PRESON_PUSH_REQUESTED = 'PRESON_PUSH_REQUESTED'
// 请求开始
export const PERSON_PUSH_REQUEST = 'PERSON_PUSH_REQUEST'
// 请求成功
export const PERSON_PUSH_SUCCEEDED = 'PERSON_PUSH_SUCCEEDED'
// 请求失败
export const PERSON_PUSH_FAILED = 'PERSON_PUSH_FAILED'
